version: 2
container_config: &container_config
  working_directory: ~/shared-fantasy-constants
  docker:
    - image: node:11.10.1
jobs:
  install:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - persist_to_workspace:
          root: ~/shared-fantasy-constants
          paths: .
  publish:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/shared-fantasy-constants
      - run:
          name: Authenticate NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish
          command: npm publish
workflows:
  version: 2
  deploy_shared_fantasy_constants:
    jobs:
      - install
      - publish:
          context: SHARED_FANTASY_CONSTANTS
          requires:
            - install
